# -*- coding: utf-8 -*-
"""First-Exercises

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAskAVD5F20e6dQLNxNUokOJu9PwA2Ay
"""

A=1200000
B=300000
C=A-B
D=6
E=C/D
print("Total_Price: ",A,"RWF")
print("Deposit_Amount: ",B,"RWF")
print("Remaining_Balance: ",C,"RWF")
print("Monthly_Installment_Amount: ",E,"RWF")

A=240000
B=3
C=A/B
print("Room_Cost: ",A,"RWF")
print("Student_Number: ",B)
print("Each_Student_Payment: ",C,"RWF")

A=2.5
B=1800
C=5
D=A*C
E=D*B
print("Total_Fuel_Consumed: ",D,"Liters")
print("Total_Fuel_Cost: ",E,"RWF")

A=85
B=50
C=A*B
print("Total_Printing_Cost: ",C,"RWF")